.TH "Card" 3 "Sun Oct 20 2019" "texasHoldem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Card\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCard\fP (int num)"
.br
.ti -1c
.RI "void \fBsetFace\fP ()"
.br
.ti -1c
.RI "void \fBsetSuit\fP ()"
.br
.ti -1c
.RI "void \fBsetPict\fP ()"
.br
.ti -1c
.RI "int \fBgetFace\fP () const"
.br
.ti -1c
.RI "int \fBgetSuit\fP () const"
.br
.ti -1c
.RI "string \fBgetFaceName\fP () const"
.br
.ti -1c
.RI "string \fBgetSuitName\fP () const"
.br
.ti -1c
.RI "string \fBgetPict\fP () const"
.br
.ti -1c
.RI "int \fBgetNumber\fP () const"
.br
.ti -1c
.RI "void \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Card\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Card::Card (int num)"

.PP
Definition at line 15 of file Card\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int Card::getFace () const\fC [inline]\fP"

.PP
Definition at line 30 of file Card\&.h\&.
.SS "string Card::getFaceName () const\fC [inline]\fP"

.PP
Definition at line 32 of file Card\&.h\&.
.SS "int Card::getNumber () const\fC [inline]\fP"

.PP
Definition at line 35 of file Card\&.h\&.
.SS "string Card::getPict () const\fC [inline]\fP"

.PP
Definition at line 34 of file Card\&.h\&.
.SS "int Card::getSuit () const\fC [inline]\fP"

.PP
Definition at line 31 of file Card\&.h\&.
.SS "string Card::getSuitName () const\fC [inline]\fP"

.PP
Definition at line 33 of file Card\&.h\&.
.SS "void Card::setFace ()"

.PP
Definition at line 32 of file Card\&.cpp\&.
.SS "void Card::setPict ()"

.PP
Definition at line 77 of file Card\&.cpp\&.
.SS "void Card::setSuit ()"

.PP
Definition at line 54 of file Card\&.cpp\&.
.SS "void Card::toString ()"

.PP
Definition at line 94 of file Card\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for texasHoldem from the source code\&.
