.TH "Hands" 3 "Sun Oct 20 2019" "texasHoldem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hands
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Hands\&.h>\fP
.PP
Inherits \fBPlayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHands\fP ()"
.br
.ti -1c
.RI "\fBHands\fP (const \fBHands\fP &orig)"
.br
.ti -1c
.RI "virtual \fB~Hands\fP ()"
.br
.ti -1c
.RI "void \fBsetFaces\fP ()"
.br
.ti -1c
.RI "void \fBsetSuits\fP ()"
.br
.ti -1c
.RI "void \fBcheckStraight\fP ()"
.br
.ti -1c
.RI "multimap< int, int, greater< int > > \fBgetFaces\fP ()"
.br
.ti -1c
.RI "map< int, int, greater< int > > \fBgetSuits\fP ()"
.br
.ti -1c
.RI "int \fBgetHands\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file Hands\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Hands::Hands ()"

.PP
Definition at line 20 of file Hands\&.cpp\&.
.SS "Hands::Hands (const \fBHands\fP & orig)"

.SS "virtual Hands::~Hands ()\fC [inline]\fP"

.PP
Definition at line 33 of file Hands\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Hands::checkStraight ()"

.PP
Definition at line 68 of file Hands\&.cpp\&.
.SS "multimap<int,int,greater<int> > Hands::getFaces ()\fC [inline]\fP"

.PP
Definition at line 39 of file Hands\&.h\&.
.SS "int Hands::getHands ()"

.PP
Definition at line 23 of file Hands\&.cpp\&.
.SS "map<int,int,greater<int> > Hands::getSuits ()\fC [inline]\fP"

.PP
Definition at line 40 of file Hands\&.h\&.
.SS "void Hands::setFaces ()"

.PP
Definition at line 187 of file Hands\&.cpp\&.
.SS "void Hands::setSuits ()"

.PP
Definition at line 160 of file Hands\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for texasHoldem from the source code\&.
