.TH "Hands.h" 3 "Sun Oct 20 2019" "texasHoldem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hands.h
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include 'Player\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHands\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for texasHoldem from the source code\&.
