.TH "Templates.h" 3 "Sun Oct 20 2019" "texasHoldem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Templates.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Card\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > void \fBswapVars\fP (T &var1, T &var2)"
.br
.ti -1c
.RI "template<class T > void \fBselectionSortVar\fP (T *var, int begin, int size)"
.br
.ti -1c
.RI "void \fBselectionSort\fP (int **array, int col, int begin, int size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void selectionSort (int ** array, int col, int begin, int size)"

.PP
Definition at line 44 of file Templates\&.h\&.
.SS "template<class T > void selectionSortVar (T * var, int begin, int size)"

.PP
Definition at line 27 of file Templates\&.h\&.
.SS "template<class T > void swapVars (T & var1, T & var2)"

.PP
Definition at line 18 of file Templates\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for texasHoldem from the source code\&.
