.TH "Hands.cpp" 3 "Sun Oct 20 2019" "texasHoldem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hands.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <set>\fP
.br
\fC#include <list>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'Hands\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for texasHoldem from the source code\&.
