.TH "main.cpp" 3 "Sun Oct 20 2019" "texasHoldem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include 'Dealer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 30 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for texasHoldem from the source code\&.
